### ISSUE TITLE
"Defining Principles for Software Engineering" article link no longer valid

### ISSUE THREAD

**Issue by 6879756e** [posquit0/awesome-engineering-team-principles#3]
Hello, I was having a look at your GitHub project and clicked on one of the links (name in the title). The url seems to no longer be valid and redirects to some adverts instead. I can't seem to find the original article despite searching for "theplainprogrammer" and article name so perhaps it would be better to omit this article? Thanks

**Comment by posquit0** [comment]
@6879756e Thanks! I updated it with a new link.
